# HYPER PARAMETERS FOR ALL GAMES
# CREATED BY SIYUEXI
# 2022.07.02
breakout: 
  name: "Breakout-v0"     # name of the environment
  type: "CRD2QN"          # type of the model
  width: 84
  height: 84
  n_actions: 4            # num of actions
  n_states: 4             # num of stacked states/frames per step
  skip: 4                 # num of skiped frames
  noop_max: 30            # num of no operation frames
  memory_capacity: 20000
  hyper_params:           # hyper_params for training only
    gamma: 0.99
    epsilon: 0.2
    batch_size: 32
    iteration: 1000000
    lr: 0.00025
    f: 4                   # parameters backward frequency
    f_save: 100000         # frequency of model saving
    f_update: 100000       # frequency of sub model updating
    f_epoch: 1000          # frequency of loss calculating
    f_episode: 100         # frequency of reward calculating
    train_start: 10000      # training starts after x epoch of experience collecting
    test_start: 1000000    # testing starts at x epoch of exploration
